### ISSUE TITLE
Assertion failed 'op->type == o_reg'

### ISSUE THREAD

**Issue by rapperskull** [n-o-o-n/idp_hexagon#13]
Hi. I compiled the module with IDA SDK 7.7, but I get an assertion error when trying to load a file. It is in ana.cpp, row 146: `assert( op->type == o_reg )`.
If I ignore it, It loads fine.

**Comment by n-o-o-n** [comment]
Please attach the binary in question.

**Comment by rapperskull** [comment]
Here you go:
https://mega.nz/file/QpUmTI5a#MhrmyUu4iqgN-Zh0CazqBXZSmZ61LPgiF9aqPSiswwc

**Comment by flowswitch** [comment]
BTW, is it a good idea to **assert()** on decode errors? An user can just press C on some data bytes and loose all work (I see rapperskul talking about ignoring an assertion, perhaps it works this way in Win version, but Linux IDA just crashes silently on asserts).
Stock IDA modules never do that, they propagate such things to ana() returning 0 instead, resulting in incorrect bytes being left as bytes.

**Comment by n-o-o-n** [comment]
> Here you go: https://mega.nz/file/QpUmTI5a#MhrmyUu4iqgN-Zh0CazqBXZSmZ61LPgiF9aqPSiswwc

In this case the issue arises from decoding some data as a code. As a result, you get
`{ memh(r18 + #0x7C) = <unknown>.new }`
The assertion error occurs due to debug compilation. I'd recommend to build module with
**m.bat NDEBUG=1**
I agree with @flowswitch that it would've been better to return 0 from ana(), but it's technically more complicated. And anyway, the result of this decoding would be reviewed by a human who will surely notice the garbage output.
